/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArsBreadcrumb: typeof import('./src/layouts/components/ArsHeader/components/ArsBreadcrumb.vue')['default']
    ArsHeader: typeof import('./src/layouts/components/ArsHeader/ArsHeader.vue')['default']
    ArsLanguages: typeof import('./src/layouts/components/ArsHeader/components/ArsLanguages.vue')['default']
    ArsLogo: typeof import('./src/layouts/components/logo/ArsLogo.vue')['default']
    ArsMenu: typeof import('./src/layouts/components/menu/ArsMenu.vue')['default']
    ArsMessage: typeof import('./src/layouts/components/ArsHeader/components/ArsMessage.vue')['default']
    ArsScreenfull: typeof import('./src/layouts/components/ArsHeader/components/ArsScreenfull.vue')['default']
    ArsSetting: typeof import('./src/layouts/components/ArsHeader/components/ArsSetting.vue')['default']
    ArsUser: typeof import('./src/layouts/components/ArsHeader/components/ArsUser.vue')['default']
    LayoutLogo: typeof import('./src/layouts/components/logo/layout-logo.vue')['default']
    LayoutMenu: typeof import('./src/layouts/components/menu/layout-menu.vue')['default']
    LayoutSider: typeof import('./src/layouts/components/sider/layout-sider.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBadge: typeof import('naive-ui')['NBadge']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NMenu: typeof import('naive-ui')['NMenu']
    NMenuItem: typeof import('naive-ui')['NMenuItem']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSubMenu: typeof import('naive-ui')['NSubMenu']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NThing: typeof import('naive-ui')['NThing']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
